### ISSUE TITLE
TTL setting is unclear according to the documentation

### ISSUE THREAD

**Issue by akvlad** [dgilland/cacheout#26]
`@cache.memoize(ttl=5, typed=True)` - default time units are never explained. So I need to look all over the code to figure out what `5` means.
`cache = Cache(maxsize=256, ttl=0, timer=time.time, default=None)  # defaults` - timer is callable I suppose. What is the specification of the callable? What should it return? 
It's a great project. In fact this is the first python cache where I see a human operatable `cache.set` method instead of intricate annotated set mechanisms (which is present as well). But ttl is my second question and it is almost not described in the documentation.

**Comment by dgilland** [comment]
The `ttl` units are dependent on what the `timer` function returns. The `timer` function is expected to return an int or float: 

https://github.com/dgilland/cacheout/blob/02940b13dc58fab8334633fa44687cfddb43e247/src/cacheout/cache.py#L63
https://github.com/dgilland/cacheout/blob/02940b13dc58fab8334633fa44687cfddb43e247/src/cacheout/cache.py#L20

Since the default `timer` function is `time.time`, then `ttl` units are seconds.

I agree that the `ttl` could be explained better in the documentation. I'll make a note to update it when I can.
