### ISSUE TITLE
on-set callback

### ISSUE THREAD

**Issue by uncle-lv** [dgilland/cacheout#37]
First of all, on-set callbcak and `RemovalCause.SET` coincide.

We can replace `RemovalCause.SET` with on-set callbcak.

```python
cache = Cache(on_set=on_set)
```

```python
Callable[[key: Hashable, new_value: Any, old_value: Any], None]
```

**Comment by dgilland** [comment]
> We can replace RemovalCause.SET with on-set callbcak.

Can you clarify what you mean here?

**Comment by uncle-lv** [comment]
on-delete callback will be called and set `RemovalCause` `RemovalCause.SET` when a key has been replaced. If we have a on-set callback, it will be called at same time. I suggest replace the on-delete callback with a on-set callback, because on-set callback is more specific.

**Comment by uncle-lv** [comment]
By the way, why is the key deleted first [here](https://github.com/dgilland/cacheout/blob/a90b5229d89c2902635ae6ef6bb86984c2c15196/src/cacheout/cache.py#L359C44-L359C44) and then set a new value instead of setting the new value directly ?

**Comment by dgilland** [comment]
> By the way, why is the key deleted first [here](https://github.com/dgilland/cacheout/blob/a90b5229d89c2902635ae6ef6bb86984c2c15196/src/cacheout/cache.py#L359C44-L359C44) and then set a new value instead of setting the new value directly ?

The underlying cache dictionary is an `OrderedDict`. When a new key is set, the key needs to be the "last" entry in the ordered key list so that the cache eviction strategies that rely on the ordering will work. So when a cache key is set, need to remove the existing key so that setting it will put the key last in the dictionary.

Why it calls `self._delete()` was more of a convenience, but now that there are cache stats and on_delete callback, it would probably be better to do the key and expiration times deletions in `self._on_set()` directly so that it doesn't interfere with stats and on-delete callback.

**Comment by dgilland** [comment]
> Why it calls `self._delete()` was more of a convenience, but now that there are cache stats and on_delete callback, it would probably be better to do the key and expiration times deletions in `self._on_set()` directly so that it doesn't interfere with stats and on-delete callback.

Actually, after reviewing the code in more detail, I think the current implementation is fine. Stats won't be modified when `_set()` calls `_delete()` and the `on_delete` callback is meant to be called.

**Comment by uncle-lv** [comment]
> > Why it calls `self._delete()` was more of a convenience, but now that there are cache stats and on_delete callback, it would probably be better to do the key and expiration times deletions in `self._on_set()` directly so that it doesn't interfere with stats and on-delete callback.
> 
> Actually, after reviewing the code in more detail, I think the current implementation is fine. Stats won't be modified when `_set()` calls `_delete()` and the `on_delete` callback is meant to be called.

Do you mean just regard `on_delete`(`RemovalCause.SET`) as on-set callback? 

But wouldn't it be better if on-set callback provided both the old and new values.
> First of all, on-set callbcak and `RemovalCause.SET` coincide.
> 
> We can replace `RemovalCause.SET` with on-set callbcak.
> 
> ```python
> cache = Cache(on_set=on_set)
> ```
> 
> ```python
> Callable[[key: Hashable, new_value: Any, old_value: Any], None]
> ```

**Comment by dgilland** [comment]
I might have misunderstood you before. Are you suggesting to get rid of the SET removal cause from on_delete and replace it with a new on_set callback? So that calling set() would only trigger the on_set callback?

If so then that makes sense. If removing the call to _delete() from within _set(), then just need to make sure that the cache key deletion and the expire times deletion are still done.

**Comment by uncle-lv** [comment]
That's what I mean. It seems that we have agreed. 🤝
